name: emrcnn-immu-pretrained
services:
  main:
    image: emrcnn-base
    build: .
    working_dir: ${PROJECT_DIR}
    command: bash run.sh
    environment:
      - PROJECT_DIR=${PROJECT_DIR}
      - DATA_NAME=immu_ensemble
      - ENSEMBLES=4
      - PRETRAINED=YES
    volumes:
      - type: bind
        source: emrcnn
        target: ${PROJECT_DIR}
      - type: bind
        source: emrcnn_release/EMR-CNN/dataset/immu
        target: ${PROJECT_DIR}/dataset/immu
      - type: bind
        source: emrcnn_release/EMR-CNN/checkpoints
        target: ${PROJECT_DIR}/checkpoints
      - type: bind
        source: .torch
        target: /root/.torch
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]